
package lotrpg;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Paths;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.plaf.IconUIResource;
import utility.Partita;
import utility.Personaggio;

/**
 *
 * @author tonin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMainMenu
     */
    public Main() {
        initComponents();
        
        setStyle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barramultifunzione = new javax.swing.JPanel();
        chiudi = new javax.swing.JButton();
        riduci = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        maxi = new javax.swing.JButton();
        restore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        screen = new javax.swing.JPanel();
        nuovapartita = new javax.swing.JButton();
        continua = new javax.swing.JButton();
        impostazioni = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        homeBackround = new javax.swing.JLabel();
        saveOption = new javax.swing.JPanel();
        titoloSaveOption = new javax.swing.JLabel();
        campoNomeSave = new javax.swing.JTextField();
        progressoScritta1 = new javax.swing.JLabel();
        progressoValore1 = new javax.swing.JLabel();
        salvataggio1 = new javax.swing.JButton();
        saveOptionBackround = new javax.swing.JLabel();
        creazionePersonaggio = new javax.swing.JPanel();
        titoloCreazionePersonaggio = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        testoNome = new javax.swing.JLabel();
        selezionaSesso = new javax.swing.JComboBox<>();
        selezionaClasse = new javax.swing.JComboBox<>();
        selezionaRazza = new javax.swing.JComboBox<>();
        selezionaAbilita = new javax.swing.JComboBox<>();
        nomeCampoNome = new javax.swing.JLabel();
        inizia = new javax.swing.JButton();
        nomeSesso = new javax.swing.JLabel();
        nomeRazza = new javax.swing.JLabel();
        miniTexturePersonaggio = new javax.swing.JLabel();
        nomeAbilita = new javax.swing.JLabel();
        nomeClasse = new javax.swing.JLabel();
        testoCorporatura = new javax.swing.JLabel();
        testoStamina = new javax.swing.JLabel();
        testoAttacco = new javax.swing.JLabel();
        TestoDIfesa = new javax.swing.JLabel();
        testoRumore = new javax.swing.JLabel();
        descrizioneAbilitaClasse = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        valoreVita = new javax.swing.JLabel();
        valoreCorporatura = new javax.swing.JLabel();
        valoreStamina = new javax.swing.JLabel();
        valoreAttacco = new javax.swing.JLabel();
        valoreDifesa = new javax.swing.JLabel();
        valoreRumore = new javax.swing.JLabel();
        StatBackround = new javax.swing.JLabel();
        creazionePersonaggioBackround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barramultifunzione.setBackground(new java.awt.Color(51, 51, 51));
        barramultifunzione.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barramultifunzioneMouseDragged(evt);
            }
        });
        barramultifunzione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barramultifunzioneMousePressed(evt);
            }
        });
        barramultifunzione.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chiudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chiudi.png"))); // NOI18N
        chiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiudiActionPerformed(evt);
            }
        });
        barramultifunzione.add(chiudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 30, 30));

        riduci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minimize-window-48.png"))); // NOI18N
        riduci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riduci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riduciActionPerformed(evt);
            }
        });
        barramultifunzione.add(riduci, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 30));

        jLabel2.setToolTipText("");
        barramultifunzione.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        maxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/maximize-window.png"))); // NOI18N
        maxi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxiActionPerformed(evt);
            }
        });
        barramultifunzione.add(maxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 30, 30));

        restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/restore-window.png"))); // NOI18N
        restore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });
        barramultifunzione.add(restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LOTRPG-30.png"))); // NOI18N
        barramultifunzione.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        getContentPane().add(barramultifunzione, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 50));

        screen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuovapartita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nuovaPartita_button.png"))); // NOI18N
        nuovapartita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuovapartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovapartitaActionPerformed(evt);
            }
        });
        screen.add(nuovapartita, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 300, 60));

        continua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/continua_button.png"))); // NOI18N
        continua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuaActionPerformed(evt);
            }
        });
        screen.add(continua, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 300, 60));

        impostazioni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/impostazioni60.png"))); // NOI18N
        screen.add(impostazioni, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 60, 60));

        title.setBackground(new java.awt.Color(204, 204, 204));
        title.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/TITLE-removebg-piccolo.png"))); // NOI18N
        title.setPreferredSize(new java.awt.Dimension(0, 0));
        screen.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 470, 130));

        homeBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/Menu-backround-piccolo.png"))); // NOI18N
        screen.add(homeBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        getContentPane().add(screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1920, 1030));

        saveOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titoloSaveOption.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titoloSaveOption.setForeground(new java.awt.Color(0, 0, 0));
        titoloSaveOption.setText("SLOT DI SALVATAGGIO");
        saveOption.add(titoloSaveOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 260, 50));

        campoNomeSave.setBackground(new java.awt.Color(102, 102, 102));
        campoNomeSave.setForeground(new java.awt.Color(255, 255, 255));
        campoNomeSave.setText("nome");
        campoNomeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeSaveActionPerformed(evt);
            }
        });
        saveOption.add(campoNomeSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, -1));

        progressoScritta1.setForeground(new java.awt.Color(0, 0, 0));
        progressoScritta1.setText("progresso:");
        saveOption.add(progressoScritta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        progressoValore1.setForeground(new java.awt.Color(0, 0, 0));
        progressoValore1.setText("new game");
        progressoValore1.setToolTipText("");
        saveOption.add(progressoValore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        salvataggio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/salvataggio-backround1.png"))); // NOI18N
        salvataggio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvataggio1.setPreferredSize(new java.awt.Dimension(170, 170));
        salvataggio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvataggio1ActionPerformed(evt);
            }
        });
        saveOption.add(salvataggio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 170));

        saveOptionBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/saveOption-backround.png"))); // NOI18N
        saveOption.add(saveOptionBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        getContentPane().add(saveOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1150, 600));

        creazionePersonaggio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titoloCreazionePersonaggio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titoloCreazionePersonaggio.setForeground(new java.awt.Color(0, 0, 0));
        titoloCreazionePersonaggio.setText("CREA PERSONAGGIO");
        creazionePersonaggio.add(titoloCreazionePersonaggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 230, 40));

        campoNome.setBackground(new java.awt.Color(111, 111, 111));
        campoNome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoNomeInputMethodTextChanged(evt);
            }
        });
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        creazionePersonaggio.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, -1));

        testoNome.setText("VITA:");
        creazionePersonaggio.add(testoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, -1));

        selezionaSesso.setBackground(new java.awt.Color(111, 111, 111));
        selezionaSesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maschio", "Femmina" }));
        selezionaSesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaSessoActionPerformed(evt);
            }
        });
        creazionePersonaggio.add(selezionaSesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, -1));

        selezionaClasse.setBackground(new java.awt.Color(111, 111, 111));
        selezionaClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerriero", "Arcere", "Guaritore", "Esploratore", "Combattente", "Avventuriero", "Cavaliere" }));
        creazionePersonaggio.add(selezionaClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 180, -1));

        selezionaRazza.setBackground(new java.awt.Color(111, 111, 111));
        selezionaRazza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elfo", "Hobbit", "Stregone", "Nano", "Uomo" }));
        selezionaRazza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selezionaRazzaItemStateChanged(evt);
            }
        });
        selezionaRazza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaRazzaActionPerformed(evt);
            }
        });
        creazionePersonaggio.add(selezionaRazza, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 180, -1));

        selezionaAbilita.setBackground(new java.awt.Color(111, 111, 111));
        selezionaAbilita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colpo Devastante", "Difesa Implacabile", "Tiro Rapido", "Occhio di Falco", "Colpo Silienzioso", "Passo Silenzioso", "Colpo d'ascia", "Resistenza di Ferro", "Carica Eroica", "Grido di Battaglia", "Luce Curativa", "Protezione Divina", "Lancio Preciso", "Furtività Avanzata" }));
        selezionaAbilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaAbilitaActionPerformed(evt);
            }
        });
        creazionePersonaggio.add(selezionaAbilita, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 400, 190, -1));

        nomeCampoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeCampoNome.setForeground(new java.awt.Color(0, 0, 0));
        nomeCampoNome.setText("Nome : ");
        creazionePersonaggio.add(nomeCampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        inizia.setBackground(new java.awt.Color(111, 111, 111));
        inizia.setText("INIZIA");
        inizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniziaActionPerformed(evt);
            }
        });
        creazionePersonaggio.add(inizia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 120, 40));

        nomeSesso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeSesso.setForeground(new java.awt.Color(0, 0, 0));
        nomeSesso.setText("Sesso :");
        creazionePersonaggio.add(nomeSesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        nomeRazza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeRazza.setForeground(new java.awt.Color(0, 0, 0));
        nomeRazza.setText("Razza :");
        creazionePersonaggio.add(nomeRazza, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        miniTexturePersonaggio.setForeground(new java.awt.Color(0, 0, 0));
        miniTexturePersonaggio.setText("Immagine Mancante");
        creazionePersonaggio.add(miniTexturePersonaggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 180, 200));

        nomeAbilita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeAbilita.setForeground(new java.awt.Color(0, 0, 0));
        nomeAbilita.setText("Abilità :");
        creazionePersonaggio.add(nomeAbilita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        nomeClasse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeClasse.setForeground(new java.awt.Color(0, 0, 0));
        nomeClasse.setText("Classe :");
        nomeClasse.setToolTipText("");
        creazionePersonaggio.add(nomeClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        testoCorporatura.setText("CORPORATURA:");
        creazionePersonaggio.add(testoCorporatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        testoStamina.setText("STAMINA:");
        creazionePersonaggio.add(testoStamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        testoAttacco.setText("ATTACCO:");
        creazionePersonaggio.add(testoAttacco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        TestoDIfesa.setText("DIFESA:");
        creazionePersonaggio.add(TestoDIfesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        testoRumore.setText("RUMORE:");
        creazionePersonaggio.add(testoRumore, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(111, 111, 111));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        descrizioneAbilitaClasse.setViewportView(jTextArea1);

        creazionePersonaggio.add(descrizioneAbilitaClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        valoreVita.setText("0");
        creazionePersonaggio.add(valoreVita, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 40, -1));

        valoreCorporatura.setText("0");
        creazionePersonaggio.add(valoreCorporatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 40, -1));

        valoreStamina.setText("0");
        creazionePersonaggio.add(valoreStamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 40, -1));

        valoreAttacco.setText("0");
        creazionePersonaggio.add(valoreAttacco, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 40, -1));

        valoreDifesa.setText("0");
        creazionePersonaggio.add(valoreDifesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 40, -1));

        valoreRumore.setText("0");
        creazionePersonaggio.add(valoreRumore, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 40, -1));

        StatBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/StatisticheBackround600x345.png"))); // NOI18N
        StatBackround.setText("jLabel3");
        creazionePersonaggio.add(StatBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 600, 345));

        creazionePersonaggioBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/GenericBackround1.png"))); // NOI18N
        creazionePersonaggio.add(creazionePersonaggioBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        getContentPane().add(creazionePersonaggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1150, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void chiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiudiActionPerformed

        this.dispose();
    }//GEN-LAST:event_chiudiActionPerformed

    private void riduciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riduciActionPerformed

        
        this.setExtendedState(this.ICONIFIED);
        
        
    }//GEN-LAST:event_riduciActionPerformed
    
    
    int xx, xy;
    private void barramultifunzioneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barramultifunzioneMouseDragged

        int x = evt.getXOnScreen();

        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-xy);

    }//GEN-LAST:event_barramultifunzioneMouseDragged

    private void barramultifunzioneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barramultifunzioneMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_barramultifunzioneMousePressed

    
    
    private final Toolkit tk = Toolkit.getDefaultToolkit();
        
    private final int w = (int)tk.getScreenSize().getWidth();
        
    private final int h = (int)tk.getScreenSize().getHeight();
    
    
    
    
    private void maxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxiActionPerformed
        
        
        //setStyleFullScreen();
        
        
        
        
    }//GEN-LAST:event_maxiActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
        
        
        
        //setStyleWindow();
        
        
        
        
    }//GEN-LAST:event_restoreActionPerformed

    private void nuovapartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovapartitaActionPerformed
        
        
        this.screen.setVisible(false);
        
        this.saveOption.setVisible(true);
        
        
        
    }//GEN-LAST:event_nuovapartitaActionPerformed

    private void continuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuaActionPerformed
        
        
        
    }//GEN-LAST:event_continuaActionPerformed

    private void salvataggio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvataggio1ActionPerformed
        
        
        this.saveOption.setVisible(false);
        
        partita1 = new Partita();
        
        if(getProgresso(save1)== 0){
            this.creazionePersonaggio.setVisible(true);
            
            
            
            personaggio1 = new Personaggio();
            
            setStatPersonaggio();
            
            getStatPersonaggio();
            
            
            
            
            
        }else{
            
            // fare partire la partita con il progresso corrente
            
        }
        
        
    }//GEN-LAST:event_salvataggio1ActionPerformed

    private void campoNomeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeSaveActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_campoNomeSaveActionPerformed

    private void iniziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniziaActionPerformed
        
        
       
        
        
        // imposta nome
        if( this.campoNome.getText()== null){
            
            //da fare pop up che avverte della mancanza di nome
            
        }else{
            setStatPersonaggio();
            
            getStatPersonaggio();
            
        }
        
        
        
        personaggio1 = new Personaggio();
        
        
        
        
        
        
    }//GEN-LAST:event_iniziaActionPerformed

    private void selezionaSessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaSessoActionPerformed
        
        setStatPersonaggio();
            
        getStatPersonaggio();
        
    }//GEN-LAST:event_selezionaSessoActionPerformed

    
    
    
    
    private void selezionaRazzaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selezionaRazzaItemStateChanged
        
        
        setStatPersonaggio();
            
        getStatPersonaggio();
        
    }//GEN-LAST:event_selezionaRazzaItemStateChanged

    private void campoNomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoNomeInputMethodTextChanged
        
        setStatPersonaggio();
            
        getStatPersonaggio();
        
    }//GEN-LAST:event_campoNomeInputMethodTextChanged

    private void selezionaAbilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaAbilitaActionPerformed
        
        setStatPersonaggio();
            
        getStatPersonaggio();
        
    }//GEN-LAST:event_selezionaAbilitaActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        setStatPersonaggio();
            
        getStatPersonaggio();
    }//GEN-LAST:event_campoNomeActionPerformed

    private void selezionaRazzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaRazzaActionPerformed
        
        setStatPersonaggio();
            
        getStatPersonaggio();
    }//GEN-LAST:event_selezionaRazzaActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    public void setStyle() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/icon/LOTRPG-100.png"));
        this.setSize(1150, 690);
        this.dispose();
        this.setUndecorated(true); 
        this.setVisible(true);
        
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth()-17, getHeight()-40, 20, 20));
        
        
        this.setLocation((w/2)-(1150/2), (h/2)-(650/2));
        
        createSaveOption();
        
        ceateCreazionePersonaggio();
        
    }
    
    
    private void createSaveOption(){
        
        this.saveOption.setSize(screen.getSize());
        
        this.saveOption.setLocation(screen.getLocation());
        
        this.saveOption.setVisible(false);
        
        if(getProgresso(save1)== 0 ){
            this.progressoValore1.setText("nuova partita");
        }else{
            
            this.progressoValore1.setText(getProgresso(save1) + "");
            
        }
        
        
        
    }
    
    
    private void ceateCreazionePersonaggio(){
        
        this.creazionePersonaggio.setSize(screen.getSize());
        
        this.creazionePersonaggio.setLocation(screen.getLocation());
        
        this.creazionePersonaggio.setVisible(false);
        
        
        
    }
    
    
    
    private void setStyleFullScreen(){
        
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth()-17, getHeight()-40, 20, 20));
        
        this.dispose();
        
        this.setSize(w, h);
        
        this.setVisible(true);
        
        // grandezza Pannelli & posizione pulsanti home
        
        barramultifunzione.setSize(1920, 50);
        
        screen.setSize(w, 1030);
        
        chiudi.setLocation(1870, 10);
        
        maxi.setLocation(1810, 10);
        
        
        
        restore.setLocation(1810, 10);
        
        riduci.setLocation(1750, 10);
        
        
        
        title.setSize(1460, 390);
        
        homeBackround.setSize(w, 1030);
        
        
    }
    
    
    private void setStyleWindow(){
        

        
        
        
        // grandezza Pannelli & posizione pulsanti home
        
        chiudi.setLocation(1870 - 900, 10);
        
        maxi.setLocation(1810 - 900, 10);
        
        
        
        restore.setLocation(1810 - 900, 10);
        
        riduci.setLocation(1750 - 900, 10);
        
        barramultifunzione.setSize(w - 900, 50);
        
        title.setSize(1460-900, 390-100);
        
        homeBackround.setSize(w-900, 1030-500);
        
        screen.setSize(w - 900, 1030 - 500);
        
        
        
    }
    
    
    private int getProgresso(String filePath){
        
        int progresso = 0;
        
        
        
        BufferedReader reader = null;

        try {
            // Apri il file e crea il BufferedReader
            reader = new BufferedReader(new FileReader(filePath));

            // Leggi il file riga per riga
            String line;
            while ((line = reader.readLine()) != null) {
                // Controlla se la riga contiene la parola "progresso: "
                if (line.contains("Progresso: ")) {
                    // Estrai il numero dopo "progresso: "
                    String progressoStr = line.split("Progresso: ")[1].trim();
                    try {
                        progresso = Integer.parseInt(progressoStr);
                        System.out.println("Il Progresso è: " + progresso);
                    } catch (NumberFormatException e) {
                        System.out.println("Formato non valido dopo 'Progresso: '");
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace(); // Stampa l'errore se non si riesce a leggere il file
        } finally {
            try {
                if (reader != null) {
                    reader.close(); // Chiudi il reader per evitare memory leak
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
        
        return progresso;
    }
    
    
    public void setStatPersonaggio(){
        
        
        personaggio1.setNome(campoNome.getText());
        
        personaggio1.setSesso(selezionaSesso.getSelectedItem().toString());
        
        personaggio1.setRazza(selezionaRazza.getSelectedItem().toString());
        
        personaggio1.setClasse(selezionaClasse.getSelectedItem().toString());
        
        personaggio1.setAbilita(selezionaAbilita.getSelectedItem().toString());
        
        personaggio1.setPersonaggioStat(selezionaRazza.getSelectedItem().toString());
        
    }
    
    public void getStatPersonaggio(){
        
        valoreVita.setText(personaggio1.getVita() + "");
        
        valoreCorporatura.setText(personaggio1.getCorporatura() + "");
        
        valoreStamina.setText(personaggio1.getStamina() + "");
        
        valoreAttacco.setText(personaggio1.getAttacco() + "");
        
        valoreDifesa.setText(personaggio1.getDifesa() + "");
        
        valoreRumore.setText(personaggio1.getRumore()+ "");
        
    }
    
    
    
    
    //variabili personali
    
    public static Personaggio personaggio1;
    public static Partita partita1;
    
    
    
    
    
    
    
    
    private String nome1;
    
    
    
    
    public static String relativePath = "src/save/save1.txt";
    public String save1 = Paths.get(relativePath).toAbsolutePath().toString();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StatBackround;
    private javax.swing.JLabel TestoDIfesa;
    private javax.swing.JPanel barramultifunzione;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeSave;
    private javax.swing.JButton chiudi;
    private javax.swing.JButton continua;
    private javax.swing.JPanel creazionePersonaggio;
    private javax.swing.JLabel creazionePersonaggioBackround;
    private javax.swing.JScrollPane descrizioneAbilitaClasse;
    private javax.swing.JLabel homeBackround;
    private javax.swing.JButton impostazioni;
    private javax.swing.JButton inizia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton maxi;
    private javax.swing.JLabel miniTexturePersonaggio;
    private javax.swing.JLabel nomeAbilita;
    private javax.swing.JLabel nomeCampoNome;
    private javax.swing.JLabel nomeClasse;
    private javax.swing.JLabel nomeRazza;
    private javax.swing.JLabel nomeSesso;
    private javax.swing.JButton nuovapartita;
    private javax.swing.JLabel progressoScritta1;
    private javax.swing.JLabel progressoValore1;
    private javax.swing.JButton restore;
    private javax.swing.JButton riduci;
    private javax.swing.JButton salvataggio1;
    private javax.swing.JPanel saveOption;
    private javax.swing.JLabel saveOptionBackround;
    private javax.swing.JPanel screen;
    private javax.swing.JComboBox<String> selezionaAbilita;
    private javax.swing.JComboBox<String> selezionaClasse;
    private javax.swing.JComboBox<String> selezionaRazza;
    private javax.swing.JComboBox<String> selezionaSesso;
    private javax.swing.JLabel testoAttacco;
    private javax.swing.JLabel testoCorporatura;
    private javax.swing.JLabel testoNome;
    private javax.swing.JLabel testoRumore;
    private javax.swing.JLabel testoStamina;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titoloCreazionePersonaggio;
    private javax.swing.JLabel titoloSaveOption;
    private javax.swing.JLabel valoreAttacco;
    private javax.swing.JLabel valoreCorporatura;
    private javax.swing.JLabel valoreDifesa;
    private javax.swing.JLabel valoreRumore;
    private javax.swing.JLabel valoreStamina;
    private javax.swing.JLabel valoreVita;
    // End of variables declaration//GEN-END:variables
}
